BrickWebStore/Controllers/CartController.cs
using BrickWebStore.DataAccess.DataContext;
using BrickWebStore.Models;
using BrickWebStore.Models.ViewModels;
using BrickWebStore.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Text;

namespace BrickWebStore.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly AppDbContext _db;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IEmailSender _emailSender;

        [BindProperty]
        public ProductUserViewModel ProductUserViewModel { get; set; }

        public CartController(
            AppDbContext appDbContext,
            IWebHostEnvironment webHostEnvironment,
            IEmailSender emailSender)
        {
            _db = appDbContext;
            _webHostEnvironment = webHostEnvironment;
            _emailSender = emailSender;
        }

        public IActionResult Index()
        {
            IEnumerable<Product> prodList;

            var prodInCart = HttpContext.Session.Get<IEnumerable<ShoppngCart>>(WC.SessionCart);

            if (prodInCart != null && prodInCart.Count() > 0)
            {
                prodList = _db.Product.Where(x => prodInCart.Select(x => x.ProductId).Contains(x.Id));
            }
            else
            {
                prodList = Enumerable.Empty<Product>();
            }

            return View(prodList);
        }

        public IActionResult Remove(int? id)
        {
            var prodInCart = HttpContext.Session.Get<ICollection<ShoppngCart>>(WC.SessionCart);

            prodInCart.Remove(prodInCart.SingleOrDefault(x => x.ProductId == id));

            HttpContext.Session.Set(WC.SessionCart, prodInCart);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost, ValidateAntiForgeryToken, ActionName("Index")]
        public IActionResult IndexPost()
        {
            return RedirectToAction(nameof(Summary));
        }


        public IActionResult Summary()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            //var userId = User.FindFirstValue(ClaimTypes.Name);

            var prodInCart = HttpContext.Session.Get<IEnumerable<ShoppngCart>>(WC.SessionCart);

            ProductUserViewModel = new ProductUserViewModel
            {
                User = _db.ShopUser.FirstOrDefault(x => x.Id == claim.Value),
                Products = prodInCart == null ? new List<Product>() : _db.Product.Where(x => prodInCart.Select(x => x.ProductId).Contains(x.Id)).ToList(),
            };

            return View(ProductUserViewModel);
        }

        [HttpPost, ValidateAntiForgeryToken, ActionName("Summary")]
        public async Task<IActionResult> SummaryPost(ProductUserViewModel productUserViewModel)
        {
            var pathToTemplate = $"{_webHostEnvironment.WebRootPath}{Path.DirectorySeparatorChar.ToString()}templates{Path.DirectorySeparatorChar.ToString()}Inquiry.html";

            var subject = "New inquery";
            var htmlBody = string.Empty;

            using (StreamReader sr = System.IO.File.OpenText(pathToTemplate))
            {
                htmlBody = sr.ReadToEnd();
            }
            var productListSb = new StringBuilder();

            foreach (var p in productUserViewModel.Products)
            {
                productListSb.Append($@" - Name: {p.ProductName} <span style=""font-size:14px""> (ID: {p.Id})</span><br/>");
            }

            var messageBody = string.Format(htmlBody,
                productUserViewModel.User.FullName,
                productUserViewModel.User.Email,
                productUserViewModel.User.PhoneNumber,
                productListSb.ToString());

            await _emailSender.SendEmailAsync(WC.EmailAdmin, subject, messageBody);

            return RedirectToAction(nameof(InqueryConfirmation));
        }

        public IActionResult InqueryConfirmation()
        {
            HttpContext.Session.Clear();

            return View();
        }
    }
}

BrickWebStore/Controllers/CategoryController.cs
using BrickWebStore.DataAccess.DataContext;
using BrickWebStore.DataAccess.Repositories.Abstractions;
using BrickWebStore.Models;
using BrickWebStore.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BrickWebStore.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class CategoryController : Controller
    {
        private readonly ICategotyRepository _categotyRepository;

        public CategoryController(ICategotyRepository categotyRepository)
        {
            _categotyRepository = categotyRepository;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> categories = _categotyRepository.GetAll();

            return View(categories);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                _categotyRepository.Add(category);

                try
                {
                    _categotyRepository.Save();
                }
                catch (Exception e)
                {
                    throw new Exception(e.Message);
                }

                return RedirectToAction("Index");
            }
            else
            {
                return View(category);
            }
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            //var obj = _db.Category.FirstOrDefault(x => x.Id == id);
            var obj = _categotyRepository.Find(id.GetValueOrDefault());

            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                _categotyRepository.Update(category);

                try
                {
                    _categotyRepository.Save();
                }
                catch (Exception e)
                {
                    throw new Exception(e.Message);
                }

                return RedirectToAction("Index");
            }
            else
            {
                return View(category);
            }
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            //var obj = _db.Category.FirstOrDefault(x => x.Id == id);
            var obj = _categotyRepository.Find(id.GetValueOrDefault());

            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _categotyRepository.FirstOrDefault(x => x.Id == id);

            if (obj == null)
            {
                return NotFound();
            }

            _categotyRepository.Remove(obj);

            try
            {
                _categotyRepository.Save();
            }
            catch (Exception e)
            {
                throw new Exception(e.Message);
            }

            return RedirectToAction("Index");
        }
    }
}

BrickWebStore/Controllers/ProductController.cs
using BrickWebStore.DataAccess.DataContext;
using BrickWebStore.Models;
using BrickWebStore.Utility;
using BrickWebStore.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BrickWebStore.DataAccess.Repositories.Abstractions;
using BrickWebStore.DataAccess.Repositories;

namespace BrickWebStore.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly IWebHostEnvironment _env;

        public ProductController(IProductRepository productRepository,
            IWebHostEnvironment env)
        {
            _productRepository = productRepository;
            _env = env;
        }

        public IActionResult Index()
        {
            IEnumerable<Product> products = _productRepository.GetAll(includProperties: "Category,BrickStore");

            return View(products);
        }

        [HttpGet]
        public IActionResult Upsert(int? id)
        {
            #region old
            //IEnumerable<SelectListItem> categoryDropDown = _db.Category.Select(x => new SelectListItem
            //{
            //    Text = x.CategoryName,
            //    Value = x.Id.ToString(),
            //});

            //ViewBag.CategoryDropDown = categoryDropDown;
            ////ViewData["CategoryDropDown"] = categoryDropDown;

            //Product product;

            //if(id == null)
            //{
            //    product = new Product();
            //}
            //else
            //{
            //    product = _db.Product.FirstOrDefault(x => x.Id == id);

            //    if(product == null)
            //    {
            //        return NotFound();
            //    }
            //}

            //return View(product);
            #endregion

            ProductViewModel productViewModel = new ProductViewModel()
            {
                Product = new Product(),
                CategorySelectList = _productRepository.GetAllDropdownList(WC.CategoryName),
                StoreAddressList = _productRepository.GetAllDropdownList(WC.BrickStoreName),
            };

            if (id != null)
            {
                var product = _productRepository.FirstOrDefault(x => x.Id == id);

                if (product != null)
                {
                    productViewModel.Product = product;
                }
                else
                {
                    return NotFound();
                }
            }

            return View(productViewModel);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductViewModel productViewModel)
        {
            string upload, fileName, extension, combinedPath;

            if (ModelState.IsValid)
            {
                var filesCount = HttpContext.Request.Form.Files.Count;
                var file = HttpContext.Request.Form.Files.FirstOrDefault();

                if (productViewModel.Product.Id == 0)
                {
                    (upload, fileName, extension, combinedPath) = GetPath(file);

                    using (var fileStream = new FileStream(combinedPath, FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }

                    productViewModel.Product.ProductImage = $"{fileName}{extension}";

                    _productRepository.Add(productViewModel.Product);
                }
                else
                {
                    var productObj = _productRepository.FirstOrDefault(x => x.Id == productViewModel.Product.Id, isTracking: false);

                    if (filesCount > 0)
                    {
                        (upload, fileName, extension, combinedPath) = GetPath(file);

                        var oldFile = Path.Combine(upload, productObj.ProductImage);

                        if (System.IO.File.Exists(oldFile))
                        {
                            System.IO.File.Delete(oldFile);
                        }

                        using (var fileStream = new FileStream(combinedPath, FileMode.Create))
                        {
                            file.CopyTo(fileStream);
                        }

                        productViewModel.Product.ProductImage = $"{fileName}{extension}";
                    }
                    else
                    {
                        productViewModel.Product.ProductImage = productObj.ProductImage;
                    }

                    _productRepository.Update(productViewModel.Product);
                }

                try
                {
                    _productRepository.Save();
                }
                catch (Exception e)
                {
                    throw new Exception(e.Message);
                }

                return RedirectToAction("Index");
            }

            productViewModel.CategorySelectList = _productRepository.GetAllDropdownList(WC.CategoryName);
            productViewModel.StoreAddressList = _productRepository.GetAllDropdownList(WC.BrickStoreName);

            return View(productViewModel);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            //var obj = _db.Category.FirstOrDefault(x => x.Id == id);
            //product.Category = _db.Category.Find(product.CategoryId);
            var product = _productRepository.FirstOrDefault(x => x.Id == id, includProperties: "Category,BrickStore");

            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        [HttpPost, ValidateAntiForgeryToken, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            var product = _productRepository.FirstOrDefault(x => x.Id == id);

            if (product == null)
            {
                return NotFound();
            }

            var imagePath = $"{_env.WebRootPath}{WC.ImagePath}{product.ProductImage}";

            if (System.IO.File.Exists(imagePath))
            {
                System.IO.File.Delete(imagePath);
            }

            _productRepository.Remove(product);

            try
            {
                _productRepository.Save();
            }
            catch (Exception e)
            {
                throw new Exception(e.Message);
            }

            return RedirectToAction("Index");
        }

        private (string, string, string, string) GetPath(IFormFile file)
        {
            var upload = $"{_env.WebRootPath}{WC.ImagePath}";
            var fileName = Guid.NewGuid().ToString();
            var extension = Path.GetExtension(file.FileName);
            var combinedPath = Path.Combine(upload, $"{fileName}{extension}");

            return (upload, fileName, extension, combinedPath);
        }
    }
}

BrickWebStore/Views/Shared/_IndividualProductCard.cshtml
@using BrickWebStore.Utility;
@model BrickWebStore.Models.Product

<div class="col-lg-4 col-md-6 pb-4 filter @Model.Category.CategoryName.Replace(' ', '_')">
    <!-- Card-->
    <div class="card bg-white rounded shadow-sm" style="border:1px solid #222">
        <div class="card-body px-3 pt-3 pb-1 row">
            <div class="col-7"><label class="float-left">@Model.ProductName</label></div>
            <div class="col-5"><label class="float-right"><span class="text-info h5">@string.Format("{0:c0}", Model.ProductPrice)</span> / sqft</label> </div>
        </div>
        <img class="card-img-top img-fluid d-block mx-auto mb-3" src="@WC.ImagePath@Model.ProductImage" alt="Card image cap">
        <div class="card-body p-1 px-3 row">
            <div class="col-6">
                <span class="badge p-2 border w-100 text-dark" style="background-color:lavenderblush">@Model.Category.CategoryName</span>
            </div>
            <div class="col-6 border-0">
                <span class="badge p-2 border w-100 text-dark" style="background-color:aliceblue">@Model.BrickStore.ShopName</span>
            </div>
            <div class="col-12 pt-2" style="font-size:13px; text-align:justify">
                <p> @Model.ShortDesk</p>
            </div>
            <div class="col-12 p-1">
                <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-dark form-control btn-sm p-2" style="height:40px">View Details</a>
            </div>
        </div>
    </div>
</div>

BrickWebStore/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using BrickWebStore.Utility
@inject IHttpContextAccessor httpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BrickWebStore</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BrickWebStore.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/fontawesom/css/all.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.css" integrity="sha256-He3QEBKoL/nMXlVsoM7S2C2kjFQqS5L+mgA+F8LpG+U=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/20.3.56/fluent.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
    

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/tile.png" width="40%"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(WC.AdminRole))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Content Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="BrickWebStore" asp-action="Index">Brick stores</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create Admin User</a>
                                </div>
                            </li>
                        }
                        <li>
                            @{
                                var sessionShoppingCarts = httpContextAccessor.HttpContext.Session.Get<List<ShoppngCart>>(WC.SessionCart);
                            }

                            @if (sessionShoppingCarts != null)
                            {
                                <a asp-action="Index" asp-controller="Cart" class="nav-link">
                                    @{
                                        var count = sessionShoppingCarts.Count;
                                    }
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (@count)
                                </a>
                            }
                            else
                            {
                                <a asp-action="Index" asp-controller="Cart" class="nav-link">
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (0)
                                </a>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark">
        <div class="container text-white-50">
            &copy; 2022 - BrickWebStore
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.syncfusion.com/ej2/20.3.56/dist/ej2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>

    <!--#region Js_links  -->
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://cdn.syncfusion.com/ej2/20.3.56/dist/ej2.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>*@
    <!--endregion -->
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>