BrickWebStore/Controllers/BrickWebStoreController.cs
using BrickWebStore.DataAccess.DataContext;
using BrickWebStore.DataAccess.Repositories.Abstractions;
using BrickWebStore.Models;
using BrickWebStore.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
namespace BrickWebStore.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class BrickWebStoreController : Controller
    {
        private readonly IBrickWebStoreRepository _brickWebStoreRepository;

        public BrickWebStoreController(IBrickWebStoreRepository brickWebStoreRepository)
        {
            _brickWebStoreRepository = brickWebStoreRepository;
        }

        public IActionResult Index()
        {
            IEnumerable<BrickWebStoreModel> stores = _brickWebStoreRepository.GetAll();

            return View(stores);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(BrickWebStoreModel brickWebStoreModel)
        {
            _brickWebStoreRepository.Add(brickWebStoreModel);

            try
            {
                _brickWebStoreRepository.Save();
            }
            catch (Exception e)
            {
                throw new Exception(e.Message);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _brickWebStoreRepository.FirstOrDefault(x => x.Id == id);
            
            if(obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult EditPost(BrickWebStoreModel brickModel)
        {
            if (ModelState.IsValid)
            {
                _brickWebStoreRepository.Update(brickModel);

                try
                {
                    _brickWebStoreRepository.Save();

                }
                catch (Exception e)
                {
                    throw new Exception(e.Message);
                }

                return RedirectToAction("Index");
            }
            else
            {
                return View(brickModel);
            }
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _brickWebStoreRepository.FirstOrDefault(x => x.Id == id);

            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        public IActionResult DeletePost(int? id)
        {
            var obj = _brickWebStoreRepository.FirstOrDefault(x => x.Id == id);
            if(obj == null)
            {
                return NotFound();
            }

            _brickWebStoreRepository.Remove(obj);

            try
            {
                _brickWebStoreRepository.Save();

            }
            catch (Exception e)
            {
                throw new Exception(e.Message);
            }

            return RedirectToAction("Index");
        }
    }
}

BrickWebStore/Views/BrickWebStore/Create.cshtml
@model BrickWebStore.Models.BrickWebStoreModel

<form method="post" asp-action="Create">
    <div class="border p-3 bg-white">
        <div class="from-group row">
            <h2 class="text-info pl-3">Add new Shop</h2>
        </div>
        <div class="row">
            <div class="row">
                <div class="col-8">
                    <div class="from-group row py-2">
                        <div class="col-4 ">
                            <label asp-for="ShopName"></label>
                        </div>
                        <div class="row-8">
                            <input asp-for="ShopName" class="form-control" />
                        </div>
                        <div class="col-4">
                            <label asp-for="Address"></label>
                        </div>
                        <div class="row-8">
                            <input asp-for="Address" class="form-control" />
                        </div>
                    </div>
                    <div class="from-group row py-2">
                        <div class="col-8 offset-4 row">
                            <div class="col">
                                <input type="submit" class="btn btn-info w-100" value="Add"/>
                            </div>
                            <div class="col">
                                <a asp-controller="BrickWebStore" asp-action="Index" class="btn btn-success w-100">
                                    <i class="fa-solid fa-arrow-right-from-bracket"></i> &nbsp; Back to shops
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

BrickWebStore/Views/BrickWebStore/Delete.cshtml
@model BrickWebStore.Models.BrickWebStoreModel

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3 bg-white">
        <div class="form-group row">
            <h2 class="text-info pl-3">Delete category</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="ShopName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="ShopName" disabled class="form-control" />
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Address"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Address" disabled class="form-control" />
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">
                                <i class="fa-solid fa-arrow-right-from-bracket"></i> &nbsp; Back to shops
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

BrickWebStore/Views/BrickWebStore/Edit.cshtml
@model BrickWebStore.Models.BrickWebStoreModel

<form method="post" asp-action="EditPost">
    <input asp-for="Id" hidden />
    <div class="border p-3 bg-white">
        <div class="form-group row">
            <h2 class="text-info pl-3">Edit category</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="ShopName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="ShopName" class="form-control" />
                        <span asp-validation-for="ShopName" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Address"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update"  />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">
                                <i class="fa-solid fa-arrow-right-from-bracket"></i> &nbsp; Back to shops
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

BrickWebStore/Views/BrickWebStore/Index.cshtml
@model IEnumerable<BrickWebStore.Models.BrickWebStoreModel>

<div class="container p-3 bg-white">
    <div class="row p-4">
        <div class="col-6">
            <h2 class="test-primary">Brick stores</h2>
        </div>
    </div>
    <div class="col-6 float-end">
        <a asp-controller="BrickWebStore" asp-action="Create" class="btn btn-primary">
            <i class="fa-solid fa-plus"></i> &nbsp; Add new shop
        </a>
    </div>

    <br /><br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Shop name
                    </th>
                    <th>
                        Display name
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var m in Model)
                {
                    <tr>
                        <td width="30%">@m.ShopName</td>
                        <td width="70%">@m.Address</td>
                <td class="test-center">
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="BrickWebStore" asp-route-Id="@m.Id" asp-action="Edit" class="btn btn-primary margin mx-2">
                                    <i class="fa-solid fa-pen-to-square"></i> &nbsp;
                                </a>
                                <a asp-controller="BrickWebStore" asp-route-Id="@m.Id" asp-action="Delete" class="btn btn-danger margin mx-2">
                                    <i class="fa-solid fa-trash"></i> &nbsp;
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>There aren't any shops now'</p>
    }

</div>